// Route: GET /
// Screen: Landing page. Explains what the simulator does, how a round works,
// and how to get started. The runs list lives at /runs.

import Link from 'next/link';

export default function LandingPage() {
  return (
    <div className="space-y-12">
      <section className="bg-white border rounded p-8">
        <h1 className="text-3xl font-semibold mb-3">The Paper Company</h1>
        <p className="text-gray-700 leading-relaxed max-w-2xl">
          A workplace simulator powered by LLMs. Configure a manager and a team of
          workers, give them personalities and a sales target, then watch them
          interact across a series of rounds. Morale shifts, output rises and
          falls, and you can drill into any avatar to see what they said and how
          it changed how they feel.
        </p>
        <div className="mt-6 flex flex-wrap gap-3">
          <Link href="/new" className="btn-primary">
            Start a new run
          </Link>
          <Link href="/runs" className="btn-secondary">
            View past runs
          </Link>
        </div>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-4">How a round works</h2>
        <ol className="space-y-3 text-sm text-gray-700">
          <Step
            n={1}
            title="A situation is drawn"
            body="Each round is tagged with a workplace situation — a deadline crunch, a team conflict, a quiet day. Every avatar in the round sees the same tag."
          />
          <Step
            n={2}
            title="The manager and workers interact"
            body="The manager talks to each worker. Workers also talk to one another in peer pairs. Every exchange is generated by the LLM in character."
          />
          <Step
            n={3}
            title="Morale updates"
            body="Each worker's morale shifts based on what was said. Manager conversations carry double weight. The manager never sees these morale numbers — they have to read the room."
          />
          <Step
            n={4}
            title="Paper gets sold"
            body="Each worker's output for the round is baseline_output × morale ÷ 50. Morale of 50 = baseline; 100 = double; 0 = nothing. Round totals roll up to the team and the run target."
          />
        </ol>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-4">Getting started</h2>
        <ol className="space-y-3 text-sm text-gray-700">
          <Step
            n={1}
            title="Configure your avatars"
            body={
              <>
                On the{' '}
                <Link href="/new" className="text-blue-700 hover:underline">
                  new run
                </Link>{' '}
                page, pick or write one manager and one or more workers. Each avatar
                has a name, a role, a personality, values, and a baseline output.
                Presets are available for common archetypes.
              </>
            }
          />
          <Step
            n={2}
            title="Set the run parameters"
            body="Choose a paper target, a number of rounds (typically 5–15), the model, and the temperature. Higher temperatures produce more varied avatar behavior."
          />
          <Step
            n={3}
            title="Run it"
            body="Click Run. The dashboard polls every two seconds and streams in rounds as they finish. A 10-round run on gpt-4o-mini takes around 40 seconds."
          />
          <Step
            n={4}
            title="Drill in"
            body="On the dashboard, click any avatar row to see their morale curve, their per-round rationale, and the full transcript of what they said and what was said to them."
          />
        </ol>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-4">Information asymmetry</h2>
        <p className="text-sm text-gray-700 leading-relaxed max-w-2xl">
          The manager never sees worker morale, baseline output, or private
          rationales — only team pace versus the target and per-worker paper sold.
          The simulator enforces this so the manager has to infer how their team is
          doing from behavior and dialogue alone, the way a real manager would.
        </p>
      </section>
    </div>
  );
}

interface StepProps {
  n: number;
  title: string;
  body: React.ReactNode;
}

function Step({ n, title, body }: StepProps) {
  return (
    <li className="flex gap-4">
      <span className="flex-shrink-0 inline-flex h-7 w-7 items-center justify-center rounded-full bg-gray-900 text-xs font-semibold text-white">
        {n}
      </span>
      <div>
        <div className="font-medium text-gray-900">{title}</div>
        <div className="mt-0.5 leading-relaxed">{body}</div>
      </div>
    </li>
  );
}
